server:
  port: 8022

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: "jdbc:postgresql://project0.cbkzfukaxelt.us-east-2.rds.amazonaws.com:5432/postgres?currentSchema=project2"
    username: postgres
    password: revature
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    serialization:
      fail-on-empty-beans: false

# ---
# server:
#   port: 8080

# spring:
#   profiles: dev #spring.profiles.active=dev
#   datasource:
#     url: jdbc:h2:file:~/test
#     driverClassName: org.h2.Driver
#     data: classpath:test-setup.sql #test-setup.sql can be put in resources folder
#   jpa:
#     show-sql: true
#     generate-ddl: true
#     properties:
#       hibernate:
#         jdbc:
#           lob:
#             non_contextual_creation: true
#   jackson:
#     serialization:
#       fail-on-empty-beans: false